AllCops:
  TargetRubyVersion: 3.2
  NewCops: enable
  Exclude:
    - '**/vendor/**/*'
    - '**/schema.rb'
    - '**/db/migrate/**'
    - '**/examples/**/*'
    - '**/bin/*'

require:
  - rubocop-rails

Style/Documentation:
  Enabled: false

Style/ClassAndModuleChildren:
  Enabled: false

Gemspec/RequiredRubyVersion:
  Enabled: false

Metrics/MethodLength:
  Max: 15

Style/AsciiComments:
  Enabled: false

Style/DoubleNegation:
  Enabled: false

Lint/RescueException:
  Enabled: false

Metrics/AbcSize:
  Max: 20

Style/YodaCondition:
  Enabled: false

Metrics/BlockLength:
  Max: 30
  Exclude:
    - 'config/environments/development.rb'
